### ISSUE TITLE
edgeId is not a queryable field

### ISSUE THREAD

**Issue by rudeb0y** [PrefectHQ/prefect-monte-carlo#28]
On usage of the module, `create_or_replace_lineage_edge` tried to return an `edgeId` but this field is not part of a [LineageGraphEdge](https://apidocs.getmontecarlo.com/#definition-LineageGraphEdge)

Returned error:

`Finished in state Failed('Flow run encountered an exception. GqlError: Cannot query field "edgeId" on type "LineageGraphEdge".')`

**Comment by zzstoatzz** [comment]
hi @rudeb0y - this has been fixed by #31 and released as v0.2.0

let us know if you encounter any issue with the change!
